// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqlPpU7IPy5HKB5NR6DIRsQOdm-eDr3u8',
    appId: '1:373255636841:web:fd48cd5e9613f76f7c9ff8',
    messagingSenderId: '373255636841',
    projectId: 'thinks-stuffs',
    authDomain: 'thinks-stuffs.firebaseapp.com',
    storageBucket: 'thinks-stuffs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFsFwSvIuRBjvy4-wLE3gwon6Z4HIukj8',
    appId: '1:373255636841:android:c05bde97112a41507c9ff8',
    messagingSenderId: '373255636841',
    projectId: 'thinks-stuffs',
    storageBucket: 'thinks-stuffs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARZcZ23S5xqvvOk8sgex2WtpEgBoLMOUw',
    appId: '1:373255636841:ios:4e4dae68001349077c9ff8',
    messagingSenderId: '373255636841',
    projectId: 'thinks-stuffs',
    storageBucket: 'thinks-stuffs.appspot.com',
    iosClientId: '373255636841-s62ttgrj9ddfe6nk32j6nkrd8j15p5ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.thingStuffs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARZcZ23S5xqvvOk8sgex2WtpEgBoLMOUw',
    appId: '1:373255636841:ios:4e4dae68001349077c9ff8',
    messagingSenderId: '373255636841',
    projectId: 'thinks-stuffs',
    storageBucket: 'thinks-stuffs.appspot.com',
    iosClientId: '373255636841-s62ttgrj9ddfe6nk32j6nkrd8j15p5ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.thingStuffs',
  );
}
